package AFCProg;

/* gramTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. gramTokenManager.java */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Iterator;
import java.util.Set;
import java.io.*;

/** Token Manager. */
@SuppressWarnings("unused")public class gramTokenManager implements gramConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 38;
            return 89;
         }
         if ((active0 & 0x6000L) != 0L)
            return 345;
         if ((active0 & 0x2000000L) != 0L)
            return 44;
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 38;
            return 178;
         }
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 38;
            return 263;
         }
         if ((active0 & 0x1000L) != 0L)
            return 3;
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 38;
            return 107;
         }
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 38;
            return 140;
         }
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 38;
            return 201;
         }
         if ((active0 & 0x430L) != 0L)
         {
            jjmatchedKind = 38;
            return 147;
         }
         if ((active0 & 0x800L) != 0L)
            return 217;
         return -1;
      case 1:
         if ((active0 & 0x3000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 1;
            return 345;
         }
         if ((active0 & 0x4800L) != 0L)
            return 345;
         if ((active0 & 0x7fcL) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 1;
            return 346;
         }
         return -1;
      case 2:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 2;
            return 345;
         }
         if ((active0 & 0x2000L) != 0L)
            return 345;
         if ((active0 & 0x608L) != 0L)
            return 346;
         if ((active0 & 0x1f4L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 2;
            return 346;
         }
         return -1;
      case 3:
         if ((active0 & 0x1000L) != 0L)
            return 345;
         if ((active0 & 0x180L) != 0L)
            return 346;
         if ((active0 & 0x74L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 3;
            return 346;
         }
         return -1;
      case 4:
         if ((active0 & 0x70L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 4;
            return 346;
         }
         if ((active0 & 0x4L) != 0L)
            return 346;
         return -1;
      case 5:
         if ((active0 & 0x70L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 5;
            return 346;
         }
         return -1;
      case 6:
         if ((active0 & 0x40L) != 0L)
            return 346;
         if ((active0 & 0x30L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 6;
            return 346;
         }
         return -1;
      case 7:
         if ((active0 & 0x30L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 7;
            return 346;
         }
         return -1;
      case 8:
         if ((active0 & 0x20L) != 0L)
            return 346;
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 8;
            return 346;
         }
         return -1;
      case 9:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 9;
            return 346;
         }
         return -1;
      case 10:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 10;
            return 346;
         }
         return -1;
      case 11:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 11;
            return 346;
         }
         return -1;
      case 12:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 12;
            return 346;
         }
         return -1;
      case 13:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 13;
            return 346;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 39:
         return jjStopAtPos(0, 29);
      case 40:
         return jjStopAtPos(0, 23);
      case 41:
         return jjStopAtPos(0, 24);
      case 43:
         return jjStopAtPos(0, 17);
      case 44:
         return jjStopAtPos(0, 28);
      case 45:
         return jjStopAtPos(0, 43);
      case 46:
         return jjStopAtPos(0, 42);
      case 58:
         jjmatchedKind = 27;
         return jjMoveStringLiteralDfa1_0(0x300000L);
      case 59:
         return jjStopAtPos(0, 18);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 61:
         return jjStopAtPos(0, 22);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x430L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 123:
         return jjStartNfaWithStates_0(0, 25, 44);
      case 125:
         return jjStopAtPos(0, 26);
      case 126:
         return jjStopAtPos(0, 19);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         break;
      case 61:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(1, 20);
         break;
      case 62:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 30);
         break;
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x8L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x430L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 86:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      case 102:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(1, 11, 345);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 114:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 14, 345);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x10L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 78:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(2, 3, 346);
         break;
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 84:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 346);
         return jjMoveStringLiteralDfa3_0(active0, 0x60L);
      case 86:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(2, 10, 346);
         break;
      case 100:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(2, 13, 345);
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 80:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 7, 346);
         else if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 346);
         break;
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x10L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 110:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 345);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x10L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 84:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(4, 2, 346);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x10L);
      case 70:
         return jjMoveStringLiteralDfa6_0(active0, 0x20L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x20L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x10L);
      case 83:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 6, 346);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x20L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(8, 5, 346);
         break;
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa10_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa11_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa13_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa14_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 83:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(14, 4, 346);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x10000000000000L, 0x0L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x0L, 0x8L
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 345;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 345:
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 147:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 201:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 107:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 140:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 178:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 263:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 39)
                        kind = 39;
                     { jjCheckNAdd(79); }
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  break;
               case 217:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 346:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 46:
                  if (curChar == 44)
                     { jjAddStates(0, 3); }
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  { jjCheckNAdd(79); }
                  break;
               case 124:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 233:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 243:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 315:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 314;
                  break;
               case 324:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 334:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 333;
                  break;
               case 336:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 335;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 44:
                  if ((0x7fffffeL & l) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 66;
                  else if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 63;
                  else if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 345:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 37)
                        kind = 37;
                     { jjCheckNAdd(76); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  break;
               case 147:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 170;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 158;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 146;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 164;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 201:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 213;
                  else if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 211;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 107:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 112;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 140:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 141;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 178:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 190;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 183;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 177;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 37)
                        kind = 37;
                     { jjCheckNAdd(76); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 263:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 343;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 327;
                  else if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 319;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 299;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 338;
                  else if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 309;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 290;
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 281;
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 271;
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  else if (curChar == 123)
                     { jjAddStates(7, 10); }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  else if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAdd(76); }
                  if (curChar == 67)
                     { jjAddStates(11, 20); }
                  else if (curChar == 98)
                     { jjAddStates(21, 22); }
                  else if (curChar == 66)
                     { jjAddStates(23, 27); }
                  else if (curChar == 105)
                     { jjAddStates(28, 29); }
                  else if (curChar == 69)
                     { jjAddStates(30, 32); }
                  else if (curChar == 68)
                     { jjAddStates(33, 36); }
                  else if (curChar == 73)
                     { jjAddStates(37, 41); }
                  else if (curChar == 65)
                     { jjAddStates(42, 43); }
                  else if (curChar == 76)
                     { jjAddStates(44, 45); }
                  else if (curChar == 80)
                     { jjAddStates(46, 47); }
                  else if (curChar == 70)
                     { jjAddStates(48, 51); }
                  else if (curChar == 84)
                     { jjAddStates(52, 53); }
                  else if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 69;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 41;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 89)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 8;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 217:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 37)
                        kind = 37;
                     { jjCheckNAdd(76); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 218;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 89:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 101;
                  else if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 92;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 88;
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 346:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     { jjCheckNAdd(78); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  break;
               case 1:
                  if (curChar == 101 && kind > 15)
                     kind = 15;
                  break;
               case 2:
               case 81:
                  if (curChar == 117)
                     { jjCheckNAdd(1); }
                  break;
               case 4:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 101 && kind > 16)
                     kind = 16;
                  break;
               case 6:
               case 87:
                  if (curChar == 115)
                     { jjCheckNAdd(5); }
                  break;
               case 7:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 117 && kind > 32)
                     kind = 32;
                  break;
               case 11:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 101 && kind > 33)
                     kind = 33;
                  break;
               case 15:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 115 && kind > 33)
                     kind = 33;
                  break;
               case 22:
               case 25:
                  if (curChar == 111)
                     { jjCheckNAdd(21); }
                  break;
               case 23:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 89)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 110 && kind > 33)
                     kind = 33;
                  break;
               case 29:
               case 108:
                  if (curChar == 111)
                     { jjCheckNAdd(28); }
                  break;
               case 30:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 116 && kind > 33)
                     kind = 33;
                  break;
               case 35:
               case 129:
                  if (curChar == 101)
                     { jjCheckNAdd(34); }
                  break;
               case 36:
                  if (curChar == 106)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 123)
                     { jjAddStates(7, 10); }
                  break;
               case 45:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  break;
               case 47:
                  if ((0x7fffffeL & l) != 0L)
                     { jjCheckNAddStates(54, 56); }
                  break;
               case 48:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(54, 56); }
                  break;
               case 49:
                  if (curChar == 125)
                     kind = 34;
                  break;
               case 50:
                  if (curChar == 100)
                     { jjCheckNAddTwoStates(46, 49); }
                  break;
               case 51:
               case 60:
                  if (curChar == 101)
                     { jjCheckNAdd(50); }
                  break;
               case 52:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
               case 62:
                  if (curChar == 114)
                     { jjCheckNAdd(50); }
                  break;
               case 54:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 109)
                     { jjCheckNAddTwoStates(46, 49); }
                  break;
               case 57:
               case 65:
                  if (curChar == 114)
                     { jjCheckNAdd(56); }
                  break;
               case 58:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 61:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 63:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 66:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 100 && kind > 35)
                     kind = 35;
                  break;
               case 69:
                  if (curChar == 101)
                     { jjCheckNAdd(68); }
                  break;
               case 70:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  break;
               case 73:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(74); }
                  break;
               case 74:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAddStates(57, 59); }
                  break;
               case 75:
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAdd(76); }
                  break;
               case 76:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 37)
                     kind = 37;
                  { jjCheckNAdd(76); }
                  break;
               case 77:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAdd(78); }
                  break;
               case 78:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAdd(78); }
                  break;
               case 80:
                  if (curChar == 84)
                     { jjAddStates(52, 53); }
                  break;
               case 82:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 69 && kind > 15)
                     kind = 15;
                  break;
               case 84:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 70)
                     { jjAddStates(48, 51); }
                  break;
               case 88:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 90:
                  if (curChar == 69 && kind > 16)
                     kind = 16;
                  break;
               case 91:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 101 && kind > 32)
                     kind = 32;
                  break;
               case 95:
                  if (curChar == 114)
                     { jjCheckNAdd(94); }
                  break;
               case 96:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 109 && kind > 35)
                     kind = 35;
                  break;
               case 101:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 80)
                     { jjAddStates(46, 47); }
                  break;
               case 104:
                  if (curChar == 108 && kind > 32)
                     kind = 32;
                  break;
               case 105:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 109:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 76)
                     { jjAddStates(44, 45); }
                  break;
               case 115:
                  if (curChar == 116)
                     { jjCheckNAdd(94); }
                  break;
               case 116:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 125:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 130:
                  if (curChar == 106)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 65)
                     { jjAddStates(42, 43); }
                  break;
               case 137:
                  if (curChar == 102 && kind > 33)
                     kind = 33;
                  break;
               case 138:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 141:
                  if (curChar == 114)
                     { jjCheckNAdd(68); }
                  break;
               case 142:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 73)
                     { jjAddStates(37, 41); }
                  break;
               case 144:
                  if (curChar == 110)
                     { jjCheckNAdd(94); }
                  break;
               case 148:
                  if (curChar == 109 && kind > 32)
                     kind = 32;
                  break;
               case 149:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 105 && kind > 33)
                     kind = 33;
                  break;
               case 152:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 114 && kind > 34)
                     kind = 34;
                  break;
               case 161:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 114 && kind > 41)
                     kind = 41;
                  break;
               case 167:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 68)
                     { jjAddStates(33, 36); }
                  break;
               case 173:
                  if (curChar == 107 && kind > 31)
                     kind = 31;
                  break;
               case 174:
               case 261:
                  if (curChar == 99)
                     { jjCheckNAdd(173); }
                  break;
               case 175:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 179:
                  if (curChar == 103 && kind > 31)
                     kind = 31;
                  break;
               case 180:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if (curChar == 112 && kind > 31)
                     kind = 31;
                  break;
               case 183:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 114 && kind > 33)
                     kind = 33;
                  break;
               case 186:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if (curChar == 69)
                     { jjAddStates(30, 32); }
                  break;
               case 193:
                  if (curChar == 115 && kind > 31)
                     kind = 31;
                  break;
               case 194:
               case 202:
               case 301:
                  if (curChar == 115)
                     { jjCheckNAdd(193); }
                  break;
               case 195:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 203:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 213:
                  if (curChar == 97)
                     { jjCheckNAdd(34); }
                  break;
               case 214:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 105)
                     { jjAddStates(28, 29); }
                  break;
               case 216:
                  if (curChar == 116 && kind > 34)
                     kind = 34;
                  break;
               case 218:
                  if (curChar == 116 && kind > 41)
                     kind = 41;
                  break;
               case 219:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 66)
                     { jjAddStates(23, 27); }
                  break;
               case 221:
                  if (curChar == 110 && kind > 32)
                     kind = 32;
                  break;
               case 222:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 117)
                     { jjCheckNAdd(94); }
                  break;
               case 227:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 234:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 111 && kind > 32)
                     kind = 32;
                  break;
               case 239:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 244:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 108 && kind > 34)
                     kind = 34;
                  break;
               case 250:
               case 256:
                  if (curChar == 111)
                     { jjCheckNAdd(249); }
                  break;
               case 251:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 108 && kind > 40)
                     kind = 40;
                  break;
               case 253:
               case 258:
                  if (curChar == 111)
                     { jjCheckNAdd(252); }
                  break;
               case 254:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 98)
                     { jjAddStates(21, 22); }
                  break;
               case 257:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 259:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 67)
                     { jjAddStates(11, 20); }
                  break;
               case 262:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 264:
                  if (curChar == 100 && kind > 31)
                     kind = 31;
                  break;
               case 265:
                  if (curChar == 101)
                     { jjCheckNAdd(264); }
                  break;
               case 266:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 109 && kind > 31)
                     kind = 31;
                  break;
               case 274:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 275:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 276:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 280:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 281:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 114)
                     { jjCheckNAdd(264); }
                  break;
               case 284:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 287:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 289:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 290:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 291:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if (curChar == 101 && kind > 31)
                     kind = 31;
                  break;
               case 293:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 294:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 295:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 296:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 297:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 298:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 299:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 300:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 302:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 303:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 304:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 306:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 307:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 308:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 309:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 310:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 311:
                  if (curChar == 116 && kind > 32)
                     kind = 32;
                  break;
               case 312:
                  if (curChar == 120)
                     { jjCheckNAdd(311); }
                  break;
               case 313:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 314:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 313;
                  break;
               case 316:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 315;
                  break;
               case 317:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 318:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 317;
                  break;
               case 319:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 318;
                  break;
               case 320:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 321:
                  if (curChar == 120 && kind > 32)
                     kind = 32;
                  break;
               case 322:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 323:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 325:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 324;
                  break;
               case 326:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 325;
                  break;
               case 327:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 328:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 327;
                  break;
               case 329:
                  if (curChar == 101)
                     { jjCheckNAdd(311); }
                  break;
               case 330:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 331:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 330;
                  break;
               case 332:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 333:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 335:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 337:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 338:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 337;
                  break;
               case 339:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 340:
                  if (curChar == 97 && kind > 32)
                     kind = 32;
                  break;
               case 341:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 340;
                  break;
               case 342:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 341;
                  break;
               case 343:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 344:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 343;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 145:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if ((jjbitVec1[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 345 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   47, 52, 55, 59, 45, 46, 49, 44, 61, 64, 67, 263, 272, 282, 291, 300, 
   310, 320, 328, 339, 344, 257, 259, 225, 237, 248, 251, 254, 217, 219, 201, 212, 
   214, 178, 181, 184, 191, 147, 150, 159, 165, 171, 140, 142, 128, 135, 107, 113, 
   89, 93, 99, 102, 82, 85, 46, 48, 49, 71, 72, 74, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, "\104\105\102\125\124", "\106\111\116", 
"\111\116\111\124\111\101\114\111\123\101\124\111\117\116\123", "\111\116\124\105\122\106\101\103\105", "\101\103\124\111\117\116\123", 
"\103\117\115\120", "\120\122\117\120", "\105\126\124", "\111\116\126", "\151\146", 
"\164\150\145\156", "\141\156\144", "\157\162", null, null, "\53", "\73", "\176", "\72\75", 
"\72\72", "\75", "\50", "\51", "\173", "\175", "\72", "\54", "\47", "\74\76", null, null, 
null, null, null, null, null, null, null, null, null, "\56", "\55", };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public gramTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public gramTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 345; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  static public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffdL, 
};
static final long[] jjtoSkip = {
   0x2L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[345];
    static private final int[] jjstateSet = new int[2 * 345];

    
    static protected char curChar;
}
